export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOAD_ENCOUNTERS = "LOAD_ENCOUNTERS";
export const REMOVE_ENCOUNTER = "REMOVE_ENCOUNTER";
export const LOAD_MONSTERS = "LOAD_MONSTERS";
export const REMOVE_MONSTER = "REMOVE_MONSTER";