export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const LOAD_ENCOUNTERS = "LOAD_ENCOUNTERS";
export const LOAD_ENCOUNTER = "LOAD_ENCOUNTER";
export const CLEAR_ENCOUNTER = "CLEAR_ENCOUNTER"
export const REMOVE_ENCOUNTER = "REMOVE_ENCOUNTER";
export const ADD_ENCOUNTER = "ADD_ENCOUNTER";

export const LOAD_MONSTERS = "LOAD_MONSTERS";
export const REMOVE_MONSTER = "REMOVE_MONSTER";
export const ADD_MONSTER = "ADD_MONSTER";

export const LOAD_WEAPONS = "LOAD_WEAPONS";
export const REMOVE_WEAPON = "REMOVE_WEAPON";
export const ADD_WEAPON = "ADD_WEAPON";

export const LOAD_MAGIC_ITEMS = "LOAD_MAGIC_ITEMS";
export const REMOVE_MAGIC_ITEM = "REMOVE_MAGIC_ITEM";
export const ADD_MAGIC_ITEM = "ADD_MAGIC_ITEM";

export const LOAD_SEARCH_RESULTS = "LOAD_SEARCH_RESULTS";
export const REMOVE_SEARCH_RESULTS = "REMOVE_SEARCH_RESULTS";
